language: bash

before_install:
    - openssl aes-256-cbc -K $encrypted_2f005ed6e83e_key -iv $encrypted_2f005ed6e83e_iv -in mykey.enc -out mykey -d

before_script:
    - curl -O https://storage.googleapis.com/contentful-dump/content-dump
    - curl -O https://storage.googleapis.com/contentful-dump/hugo
    - chmod 755 content-dump hugo

script: bash ./deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: "2f005ed6e83e"
  - COMMIT_AUTHOR_EMAIL: "adriaandejonge@gmail.com"