language: bash

before_install:
    - openssl aes-256-cbc -K $encrypted_2f005ed6e83e_key -iv $encrypted_2f005ed6e83e_iv -in mykey.enc -out mykey -d

before_script:
    - curl -OL https://github.com/adriaandejonge/contentful-hugo/releases/download/0.2/contentful-hugo_0.2_Linux-64bit.tar.gz
    - curl -OL https://github.com/gohugoio/hugo/releases/download/v0.26/hugo_0.26_Linux-64bit.tar.gz
    - tar -xzvf contentful*.tar.gz
    - tar -xzvf hugo*.tar.gz
    - chmod 755 contentful-hugo hugo

script: bash ./deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: "2f005ed6e83e"
  - COMMIT_AUTHOR_EMAIL: "adriaandejonge@gmail.com"