language: bash

before_install:
    - openssl aes-256-cbc -K $encrypted_2f005ed6e83e_key -iv $encrypted_2f005ed6e83e_iv -in mykey.enc -out mykey -d

before_script:
    - curl -OL https://github.com/adriaandejonge/contentful-hugo/releases/download/$EXTRACTOR_VERSION/contentful-hugo_$EXTRACTOR_VERSION_Linux-64bit.tar.gz
    - curl -OL https://github.com/gohugoio/hugo/releases/download/v$HUGO_VERSION/hugo_$HUGO_VERSION_Linux-64bit.tar.gz
    - tar -xzvf contentful*.tar.gz
    - tar -xzvf hugo*.tar.gz
    - chmod 755 contentful-hugo hugo

script: bash ./deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: "2f005ed6e83e"
  - COMMIT_AUTHOR_EMAIL: "adriaandejonge@gmail.com"
  - HUGO_VERSION: "0.27.1"
  - EXTRACTOR_VERSION: "0.2.1"