baseURL = "https://adriaandejonge.github.io/test-travis/"
languageCode = "en-us"
title = "My New Test Site"
theme = "ananke"

[params]
    #mainSections = "elements"

[permalinks]
  smallgroup = "/smallgroup/:slug/"    